CREATE DATABASE WebBanSach

GO
USE WebBanSach

go
create table TAIKHOANADMIN
(
	ID_ADMIN int IDENTITY(0,1),
	SDT_ADMIN NVARCHAR(20) NOT NULL,
	MATKHAU NVARCHAR(20) NOT NULL,
	CONSTRAINT PK_IDAD PRIMARY KEY(ID_ADMIN),
)

GO 
CREATE TABLE TK_KHACHHANG
(
	ID_KHACHHANG INT IDENTITY(0,1),
	HOTENKH NVARCHAR(50) NOT NULL,
	SDT_KH NVARCHAR(20) NOT NULL,
	DIACHI NVARCHAR(50) NULL,
	MATKHAU_KH NVARCHAR(20) NOT NULL,
	CONSTRAINT PK_IDKH PRIMARY KEY(ID_KHACHHANG),
)

go
CREATE TABLE TACGIA
(
	MATACGIA int IDENTITY(0,1),
	TENTACGIA NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_MATG PRIMARY KEY(MATACGIA),
)

GO
CREATE TABLE NXB
(
	MANXB int IDENTITY(0,1),
	TENNXB NVARCHAR(100) NOT NULL,  
	CONSTRAINT PK_NXB PRIMARY KEY(MANXB),
)
CREATE TABLE NHACC
(
	MANCC int IDENTITY(0,1),
	TENNCC NVARCHAR(100) NOT NULL,  
	SDT NVARCHAR(100) NOT NULL, 
	DIACHI NVARCHAR(100) NOT NULL, 
	CONSTRAINT PK_NCC PRIMARY KEY(MANCC),
)

GO
CREATE TABLE THELOAI
(
	MATHELOAI int IDENTITY(0,1),
	TENTHELOAI NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_MATHELOAI PRIMARY KEY(MATHELOAI),   
)

GO
CREATE TABLE SACH
(
	MASACH int IDENTITY(0,1),
	TENSACH NVARCHAR(50) NOT NULL,
	NGUOIDICH NVARCHAR(50) NULL,
	NGONNGU NVARCHAR(50) NOT NULL,
	SOTRANG INT NOT NULL,
	TRONGLUONG INT NOT NULL,
	NAMXUATBAN NVARCHAR(10) NOT NULL,
	KICHTHUOC NVARCHAR(50) NOT NULL,
	MATACGIA INT NOT NULL,
	MATHELOAI INT NULL,
	MANXB INT NULL,
	TENANH NVARCHAR(100) NOT NULL,
	GIANHAP INT NOT NULL,
	GIABAN INT NOT NULL,
	SOLUONG INT NULL,
	CONSTRAINT PK_SACH PRIMARY KEY(MASACH),   
	CONSTRAINT FK_NXB FOREIGN KEY(MANXB) REFERENCES NXB(MANXB),
	CONSTRAINT FK_MATHELOAI FOREIGN KEY(MATHELOAI) REFERENCES THELOAI(MATHELOAI),
	CONSTRAINT FK_MATG FOREIGN KEY(MATACGIA) REFERENCES TACGIA(MATACGIA),
)

GO
CREATE TABLE HOADONBAN
(
	MAHDBAN int IDENTITY(0,1),
	NGAYLAPHDBAN DATE NULL,
	ID_KHACHHANG INT NOT NULL,
	CONSTRAINT PK_MAHDBAN PRIMARY KEY(MAHDBAN),
	CONSTRAINT FK_MAKH FOREIGN KEY(ID_KHACHHANG) REFERENCES TK_KHACHHANG(ID_KHACHHANG),
)

GO
CREATE TABLE CT_HDBAN
(
	MACT_HDB int IDENTITY(0,1),
	MASACH INT NOT NULL,
	MAHDBAN INT NOT NULL,
	SLBAN INT NOT NULL,
	KHUYENMAI NVARCHAR(20) NULL,
	CONSTRAINT PK_MACT_HDB PRIMARY KEY(MACT_HDB),
	CONSTRAINT FK_MS FOREIGN KEY(MASACH) REFERENCES SACH(MASACH),
	CONSTRAINT FK_HDBAN FOREIGN KEY(MAHDBAN) REFERENCES HOADONBAN(MAHDBAN),
)
GO
CREATE TABLE HOADONNHAP
(
	MAHDNHAP int IDENTITY(0,1),
	NGAYLAPHDNHAP DATE NULL,
	MANCC INT NULL,
	CONSTRAINT PK_HDNHAP PRIMARY KEY(MAHDNHAP),
	CONSTRAINT FK_MANCC FOREIGN KEY(MANCC) REFERENCES NHACC(MANCC),
)
GO
CREATE TABLE CT_HDNHAP
(
	MACT_HDN int IDENTITY(0,1),
	MASACH INT NOT NULL,
	MAHDNHAP INT NOT NULL,
	SLNHAP INT NOT NULL,
	CONSTRAINT PK_MACT_HDN PRIMARY KEY(MACT_HDN),
	CONSTRAINT FK_MSACH FOREIGN KEY(MASACH) REFERENCES SACH(MASACH),
	CONSTRAINT FK_HDNHAP FOREIGN KEY(MAHDNHAP) REFERENCES HOADONNHAP(MAHDNHAP),
)

GO
CREATE TABLE GIOHANG
(
	ID_GIOHANG int IDENTITY(0,1),
	ID_KHACHHANG INT NOT NULL,
	MASACH INT NOT NULL,
	SOLUONG INT NOT NULL,
	CONSTRAINT PK_GH PRIMARY KEY(ID_GIOHANG),
	CONSTRAINT FK_GH_MSACH FOREIGN KEY(MASACH) REFERENCES SACH(MASACH),
	CONSTRAINT FK_GH_MAKH FOREIGN KEY(ID_KHACHHANG) REFERENCES TK_KHACHHANG(ID_KHACHHANG),
)

ALTER TABLE [TK_KHACHHANG] NOCHECK CONSTRAINT ALL
GO
INSERT [dbo].[TK_KHACHHANG] ( [HOTENKH], SDT_KH, [DIACHI], [MATKHAU_KH]) VALUES (N'Trần Văn Nam', N'0326985425', N'Thanh Xuân - Hà Nội', '123')
INSERT [dbo].[TK_KHACHHANG] ( [HOTENKH], SDT_KH, [DIACHI], [MATKHAU_KH]) VALUES (N'Vũ Thu Ngọc', N'0945236514', N'Yên Bái', '123')
INSERT [dbo].[TK_KHACHHANG] ( [HOTENKH], SDT_KH, [DIACHI], [MATKHAU_KH]) VALUES (N'Ðồng Thị Hồng Nhung', N'0865326958', N'Ðồng Nai', '123')
INSERT [dbo].[TK_KHACHHANG] ( [HOTENKH], SDT_KH, [DIACHI], [MATKHAU_KH]) VALUES (N'Nguyễn Thị Hà', N'0953215264', N'Quận 2 - TP Hồ Chí Minh', '123')
INSERT [dbo].[TK_KHACHHANG] ( [HOTENKH], SDT_KH, [DIACHI], [MATKHAU_KH]) VALUES (N'Ngô Hoài Long', N'0968326125', N'Ðắc Lắc', '123')
INSERT [dbo].[TK_KHACHHANG] ( [HOTENKH], SDT_KH, [DIACHI], [MATKHAU_KH]) VALUES (N'Trần Thị Hoa', N'0192985425', N'Ba Ðình - Hà Nội', '123')
INSERT [dbo].[TK_KHACHHANG] ( [HOTENKH], SDT_KH, [DIACHI], [MATKHAU_KH]) VALUES (N'Nguyễn Minh Quang', N'0326436514', N'Thanh Hóa', '123')
INSERT [dbo].[TK_KHACHHANG] ( [HOTENKH], SDT_KH, [DIACHI], [MATKHAU_KH]) VALUES (N'Lê Van Mạnh', N'0965126958', N'Lai Châu', '123')
INSERT [dbo].[TK_KHACHHANG] ( [HOTENKH], SDT_KH, [DIACHI], [MATKHAU_KH]) VALUES (N'Nguyễn Hoài Nam', N'0958521426', N'Quận 1 - TP H? Chí Minh', '123')
INSERT [dbo].[TK_KHACHHANG] ( [HOTENKH], SDT_KH, [DIACHI], [MATKHAU_KH]) VALUES ( N'Ngô Ngọc Hà', N'0125426125', N'Cầu Giấy - Hà Nội', '123')

ALTER TABLE [NHACC] NOCHECK CONSTRAINT ALL
GO
INSERT [dbo].[NHACC] ( [TENNCC], [SDT], [DIACHI]) VALUES ( N'Nhà sách Fahasa', N'0326458712', N'Quận 1 - TP Hồ Chí Minh')
INSERT [dbo].[NHACC] ( [TENNCC], [SDT], [DIACHI]) VALUES (N'VBooks', N'0541698754', N'Ba Ðình - Hà Nội')
INSERT [dbo].[NHACC] ( [TENNCC], [SDT], [DIACHI]) VALUES (N'Phương Ðông Books', N'0985632541', N'Hai Bà Trung - Hà N?i ')
INSERT [dbo].[NHACC] ( [TENNCC], [SDT], [DIACHI]) VALUES ( N'Tân Việt', N'0365236985', N'Hoài Ðức - Hà Nội')
INSERT [dbo].[NHACC] ( [TENNCC], [SDT], [DIACHI]) VALUES ( N'Nhân Văn', N'0915487215', N'Tân Phú - Hồ Chí Minh')

ALTER TABLE [NXB] NOCHECK CONSTRAINT ALL
GO
INSERT [dbo].[NXB] ( [TENNXB]) VALUES (N'NXB Hội Nhà Văn')
INSERT [dbo].[NXB] ( [TENNXB]) VALUES ( N'NXB Trẻ')
INSERT [dbo].[NXB] ( [TENNXB]) VALUES ( N'NXB Phụ Nữ')
INSERT [dbo].[NXB] ( [TENNXB]) VALUES ( N'NXB Xây Dựng')
INSERT [dbo].[NXB] ( [TENNXB]) VALUES ( N'NXB Chính Trị Quốc Gia Sự Thật')
INSERT [dbo].[NXB] ( [TENNXB]) VALUES ( N'NXB Thông Tin Và Truyền Thông')
INSERT [dbo].[NXB] ( [TENNXB]) VALUES ( N'NXB Dân Trí')
INSERT [dbo].[NXB] ( [TENNXB]) VALUES ( N'NXB Giáo dục')
INSERT [dbo].[NXB] ( [TENNXB]) VALUES ( N'NXB ĐH Quốc gia')
INSERT [dbo].[NXB] ( [TENNXB]) VALUES ( N'NXB Văn học')
INSERT [dbo].[NXB] ( [TENNXB]) VALUES ( N'NXB Khoa học kỹ thuật')
INSERT [dbo].[NXB] ( [TENNXB]) VALUES ( N'NXB Hà Nội')
INSERT [dbo].[NXB] ( [TENNXB]) VALUES ( N'NXB Tri thức')
INSERT [dbo].[NXB] ( [TENNXB]) VALUES ( N'NXB Bách Khoa - Hà Nội')


ALTER TABLE [TACGIA] NOCHECK CONSTRAINT ALL
GO
INSERT [dbo].[TACGIA] ( [TENTACGIA]) VALUES ( N'Nguyễn Nhật Ánh')
INSERT [dbo].[TACGIA] ( [TENTACGIA]) VALUES ( N'Nguyên Phong')
INSERT [dbo].[TACGIA] ( [TENTACGIA]) VALUES ( N'Lê Van Cừ')
INSERT [dbo].[TACGIA] ( [TENTACGIA]) VALUES ( N'Bộ Giáo Dục Và Ðào Tạo')
INSERT [dbo].[TACGIA] ( [TENTACGIA]) VALUES ( N'Anthony William')
INSERT [dbo].[TACGIA] ( [TENTACGIA]) VALUES ( N'Paulo Coelho')
INSERT [dbo].[TACGIA] ( [TENTACGIA]) VALUES ( N'Nguyên Hồng')
INSERT [dbo].[TACGIA] ( [TENTACGIA]) VALUES ( N'Lê Văn Phùng')
INSERT [dbo].[TACGIA] ( [TENTACGIA]) VALUES ( N'Dale Carnegie')
INSERT [dbo].[TACGIA] ( [TENTACGIA]) VALUES ( N'Viên Quảng Quân')
INSERT [dbo].[TACGIA] ( [TENTACGIA]) VALUES ( N'GS.TS. Nguyễn Trọng Uyển')
INSERT [dbo].[TACGIA] ( [TENTACGIA]) VALUES ( N'Nhóm phân tích kinh tế')
INSERT [dbo].[TACGIA] ( [TENTACGIA]) VALUES ( N'TS. Phạm Huy Hoàng')
INSERT [dbo].[TACGIA] ( [TENTACGIA]) VALUES ( N'Bộ Thông tin và Truyền thông')
INSERT [dbo].[TACGIA] ( [TENTACGIA]) VALUES ( N'Andrew Matthews')
INSERT [dbo].[TACGIA] ( [TENTACGIA]) VALUES ( N'Robert Kiyosaki')
INSERT [dbo].[TACGIA] ( [TENTACGIA]) VALUES ( N'Edmondo De Amicis')
INSERT [dbo].[TACGIA] ( [TENTACGIA]) VALUES ( N'Nicolas Windpassinger')

ALTER TABLE [THELOAI] NOCHECK CONSTRAINT ALL
GO
INSERT [dbo].[THELOAI] ( [TENTHELOAI]) VALUES ( N'Văn học')
INSERT [dbo].[THELOAI] ( [TENTHELOAI]) VALUES ( N'Kĩ năng sống')
INSERT [dbo].[THELOAI] ( [TENTHELOAI]) VALUES ( N'Khoa học - kĩ thuật')
INSERT [dbo].[THELOAI] ( [TENTHELOAI]) VALUES ( N'Công nghệ thông tin')
INSERT [dbo].[THELOAI] ( [TENTHELOAI]) VALUES ( N'Y học')
INSERT [dbo].[THELOAI] ( [TENTHELOAI]) VALUES ( N'Khoa học - Công nghệ')
INSERT [dbo].[THELOAI] ( [TENTHELOAI]) VALUES ( N'Nghệ thuật')
INSERT [dbo].[THELOAI] ( [TENTHELOAI]) VALUES ( N'Tiểu thuyết')
INSERT [dbo].[THELOAI] ( [TENTHELOAI]) VALUES ( N'Trinh thám')
INSERT [dbo].[THELOAI] ( [TENTHELOAI]) VALUES ( N'Giáo khoa - Giáo trình')
INSERT [dbo].[THELOAI] ( [TENTHELOAI]) VALUES ( N'Văn học nghệ thuật')
INSERT [dbo].[THELOAI] ( [TENTHELOAI]) VALUES ( N'Chính trị – pháp luật')
INSERT [dbo].[THELOAI] ( [TENTHELOAI]) VALUES ( N'Sách thiếu nhi')
INSERT [dbo].[THELOAI] ( [TENTHELOAI]) VALUES ( N'Văn hóa xã hội – Lịch sử')

ALTER TABLE [SACH] NOCHECK CONSTRAINT ALL
GO
INSERT [dbo].[SACH] ( [TENSACH], [NGUOIDICH], [NGONNGU], [SOTRANG], [TRONGLUONG], [NAMXUATBAN], [KICHTHUOC], [MATHELOAI], [MATACGIA], [MANXB], [GIANHAP], [GIABAN], [TENANH], [SOLUONG]) VALUES ( N'Nhà giả kim', N'Lê Chu Cầu', N'Bồ Ðào Nha', 225, 220, N'2020', N'20.5 x 13cm', 0, 5, 0, 50000, 70000, '01.jpg', 20)
INSERT [dbo].[SACH] ( [TENSACH], [NGUOIDICH], [NGONNGU], [SOTRANG], [TRONGLUONG], [NAMXUATBAN], [KICHTHUOC], [MATHELOAI], [MATACGIA], [MANXB], [GIANHAP], [GIABAN], [TENANH], [SOLUONG]) VALUES ( N'Con Chim Xanh Biếc Bay Về', NULL, N'Tiếng Việt', 396, 270, N'2020', N'13 x 20cm', 0, 0, 1, 70000, 101000, '22.jpg', 30)
INSERT [dbo].[SACH] ( [TENSACH], [NGUOIDICH], [NGONNGU], [SOTRANG], [TRONGLUONG], [NAMXUATBAN], [KICHTHUOC], [MATHELOAI], [MATACGIA], [MANXB], [GIANHAP], [GIABAN], [TENANH], [SOLUONG]) VALUES ( N'Những Ngày Thơ Ấu', NULL, N'Tiếng Việt', 215, 196, N'2019', N'14.5 x 20.5cm', 0, 6, 0, 19000, 40000, '03.jpg', 50)
INSERT [dbo].[SACH] ( [TENSACH], [NGUOIDICH], [NGONNGU], [SOTRANG], [TRONGLUONG], [NAMXUATBAN], [KICHTHUOC], [MATHELOAI], [MATACGIA], [MANXB], [GIANHAP], [GIABAN], [TENANH], [SOLUONG]) VALUES ( N'Rèn Luyện Tư Duy Phản Biện', N'Nam Phuong', N'Mỹ', 204, 300, N'2019', N'13 x 19 cm', 1, 4, 2, 54000, 99000, '04.jpg', 10)
INSERT [dbo].[SACH] ( [TENSACH], [NGUOIDICH], [NGONNGU], [SOTRANG], [TRONGLUONG], [NAMXUATBAN], [KICHTHUOC], [MATHELOAI], [MATACGIA], [MANXB], [GIANHAP], [GIABAN], [TENANH], [SOLUONG]) VALUES ( N'Trở Về Từ Cõi Sáng', NULL, N'Tiếng Việt', 208, 248, N'2019', N'14 x 20.5 cm', 1, 1, 0, 40000, 88000, '05.jpg', 15)
INSERT [dbo].[SACH] ( [TENSACH], [NGUOIDICH], [NGONNGU], [SOTRANG], [TRONGLUONG], [NAMXUATBAN], [KICHTHUOC], [MATHELOAI], [MATACGIA], [MANXB], [GIANHAP], [GIABAN], [TENANH], [SOLUONG]) VALUES ( N'Hoa Sen Trên Tuyết', NULL, N'Tiếng Việt', 196, 185, N'2021', N'14.5 x 20.5 cm', 1, 1, 0, 30000, 98000, '06.jpg', 25)
INSERT [dbo].[SACH] ( [TENSACH], [NGUOIDICH], [NGONNGU], [SOTRANG], [TRONGLUONG], [NAMXUATBAN], [KICHTHUOC], [MATHELOAI], [MATACGIA], [MANXB], [GIANHAP], [GIABAN], [TENANH], [SOLUONG]) VALUES ( N'Ðộng Lực Học Đường Sắt Cao Tốc Ứng Dụng', NULL, N'Tiếng Việt', 287, 430, N'2019', N'14 x 20 cm', 2, 2, 3, 40000, 93500, '07.jpg', 35)
INSERT [dbo].[SACH] ( [TENSACH], [NGUOIDICH], [NGONNGU], [SOTRANG], [TRONGLUONG], [NAMXUATBAN], [KICHTHUOC], [MATHELOAI], [MATACGIA], [MANXB], [GIANHAP], [GIABAN], [TENANH], [SOLUONG]) VALUES ( N'Giáo Trình Kinh Tế Chính Trị Mác – Lênin', NULL, N'Tiếng Việt', 292, 250, N'2021', N'13 x 20 cm', 2, 3, 4, 30000, 60000, '08.jpg', 40)
INSERT [dbo].[SACH] ( [TENSACH], [NGUOIDICH], [NGONNGU], [SOTRANG], [TRONGLUONG], [NAMXUATBAN], [KICHTHUOC], [MATHELOAI], [MATACGIA], [MANXB], [GIANHAP], [GIABAN], [TENANH], [SOLUONG]) VALUES ( N'An toàn thông tin', NULL, N'Tiếng Việt', 345, 400, N'2022', N'15 x 24 cm', 3, 7, 5, 35000, 84000, '09.jpg', 50)
INSERT [dbo].[SACH] ( [TENSACH], [NGUOIDICH], [NGONNGU], [SOTRANG], [TRONGLUONG], [NAMXUATBAN], [KICHTHUOC], [MATHELOAI], [MATACGIA], [MANXB], [GIANHAP], [GIABAN], [TENANH], [SOLUONG]) VALUES ( N'Cơ Thể Tự Chữa Lành', N'Ngọc Linh', N'Mỹ', 760, 1500, N'2022', N'19 x 24 cm', 4, 4, 1, 150000, 233000, '10.jpg', 60)
INSERT [dbo].[SACH] ( [TENSACH], [NGUOIDICH], [NGONNGU], [SOTRANG], [TRONGLUONG], [NAMXUATBAN], [KICHTHUOC], [MATHELOAI], [MATACGIA], [MANXB], [GIANHAP], [GIABAN], [TENANH], [SOLUONG]) VALUES ( N'Đời Thay đổi khi chúng ta thay đổi', NULL, N'Tiếng Việt', 130, 500, N'2020', N'20.5 x 24 cm', 5, 9, 6, 50000, 23000, '11.jpg', 15)
INSERT [dbo].[SACH] ( [TENSACH], [NGUOIDICH], [NGONNGU], [SOTRANG], [TRONGLUONG], [NAMXUATBAN], [KICHTHUOC], [MATHELOAI], [MATACGIA], [MANXB], [GIANHAP], [GIABAN], [TENANH], [SOLUONG]) VALUES ( N'Dạy con làm giàu', NULL, N'Tiếng Việt', 170, 60, N'2021', N'13 x 20 cm', 6, 8, 13, 55000, 34000, '12.jpg', 30)
INSERT [dbo].[SACH] ( [TENSACH], [NGUOIDICH], [NGONNGU], [SOTRANG], [TRONGLUONG], [NAMXUATBAN], [KICHTHUOC], [MATHELOAI], [MATACGIA], [MANXB], [GIANHAP], [GIABAN], [TENANH], [SOLUONG]) VALUES ( N'Những tấm lòng cao cả', NULL, N'Tiếng Việt', 460, 230, N'2022', N'19 x 24 cm', 2, 10, 7, 150000, 90000, '23.jpg', 45)
INSERT [dbo].[SACH] ( [TENSACH], [NGUOIDICH], [NGONNGU], [SOTRANG], [TRONGLUONG], [NAMXUATBAN], [KICHTHUOC], [MATHELOAI], [MATACGIA], [MANXB], [GIANHAP], [GIABAN], [TENANH], [SOLUONG]) VALUES ( N'Cho tôi xin 1 vé đi tuổi thơ', NULL, N'Tiếng Việt', 200, 100, N'2019', N'14 x 20 cm', 10, 12, 9, 80000, 30000, '14.jpg', 50)
INSERT [dbo].[SACH] ( [TENSACH], [NGUOIDICH], [NGONNGU], [SOTRANG], [TRONGLUONG], [NAMXUATBAN], [KICHTHUOC], [MATHELOAI], [MATACGIA], [MANXB], [GIANHAP], [GIABAN], [TENANH], [SOLUONG]) VALUES ( N'Internet vạn vật Chuyển đổi hay là chết', N'Mai Hạnh', N'Mỹ', 205, 155 ,N'2022', N'19 x 20.5 cm', 9, 11, 8, 60000, 35000, '15.jpg', 20)
INSERT [dbo].[SACH] ( [TENSACH], [NGUOIDICH], [NGONNGU], [SOTRANG], [TRONGLUONG], [NAMXUATBAN], [KICHTHUOC], [MATHELOAI], [MATACGIA], [MANXB], [GIANHAP], [GIABAN], [TENANH], [SOLUONG]) VALUES ( N'Cơ học Kết cấu tập 1 Hệ tĩnh định', N'Hải Đăng', N'Nga', 415, 760, N'2018', N'13 x 20 cm', 5, 16, 11, 175000, 105000, '16.jpg', 22)
INSERT [dbo].[SACH] ( [TENSACH], [NGUOIDICH], [NGONNGU], [SOTRANG], [TRONGLUONG], [NAMXUATBAN], [KICHTHUOC], [MATHELOAI], [MATACGIA], [MANXB], [GIANHAP], [GIABAN], [TENANH], [SOLUONG]) VALUES ( N'Kỹ thuật chẩn đoán lỗi', NULL, N'Tiếng Việt', 320, 145, N'2021', N'14.5 x 20 cm', 8, 12, 11, 127000, 85000, '17.jpg', 34)
INSERT [dbo].[SACH] ( [TENSACH], [NGUOIDICH], [NGONNGU], [SOTRANG], [TRONGLUONG], [NAMXUATBAN], [KICHTHUOC], [MATHELOAI], [MATACGIA], [MANXB], [GIANHAP], [GIABAN], [TENANH], [SOLUONG]) VALUES ( N'Hóa Học Vô Cơ Phần 1 Các Nguyên Tố', N'Nghĩa Lợi', N'Nga', 377, 180, N'2020', N'19 x 20 cm', 8, 12, 11, 135000, 70000, '18.jpg', 32)
INSERT [dbo].[SACH] ( [TENSACH], [NGUOIDICH], [NGONNGU], [SOTRANG], [TRONGLUONG], [NAMXUATBAN], [KICHTHUOC], [MATHELOAI], [MATACGIA], [MANXB], [GIANHAP], [GIABAN], [TENANH], [SOLUONG]) VALUES ( N'Big Data, Tuyển Tập Dữ Liệu Lớn', NULL, N'Tiếng Việt', 450, 270, N'2019', N'13 x 20.5 cm', 5, 16, 11, 200000, 154000, '19.jpg', 20)

ALTER TABLE [HOADONBAN] NOCHECK CONSTRAINT ALL
GO
INSERT [dbo].[HOADONBAN] ( [NGAYLAPHDBAN], [ID_KHACHHANG]) VALUES (N'2021-04-13', 0)
INSERT [dbo].[HOADONBAN] ( [NGAYLAPHDBAN], [ID_KHACHHANG]) VALUES (N'2021-04-13', 1)
INSERT [dbo].[HOADONBAN] ( [NGAYLAPHDBAN], [ID_KHACHHANG]) VALUES (N'2021-12-01', 2)
INSERT [dbo].[HOADONBAN] ( [NGAYLAPHDBAN], [ID_KHACHHANG]) VALUES (N'2021-07-13', 3)
INSERT [dbo].[HOADONBAN] ( [NGAYLAPHDBAN], [ID_KHACHHANG]) VALUES (N'2021-09-13', 4)
INSERT [dbo].[HOADONBAN] ( [NGAYLAPHDBAN], [ID_KHACHHANG]) VALUES (N'2022-02-14', 5)
INSERT [dbo].[HOADONBAN] ( [NGAYLAPHDBAN], [ID_KHACHHANG]) VALUES (N'2022-03-15', 6)
INSERT [dbo].[HOADONBAN] ( [NGAYLAPHDBAN], [ID_KHACHHANG]) VALUES (N'2020-04-25', 7)
INSERT [dbo].[HOADONBAN] ( [NGAYLAPHDBAN], [ID_KHACHHANG]) VALUES (N'2021-03-20', 8)
INSERT [dbo].[HOADONBAN] ( [NGAYLAPHDBAN], [ID_KHACHHANG]) VALUES (N'2022-03-18', 9)

ALTER TABLE [HOADONNHAP] NOCHECK CONSTRAINT ALL
GO
INSERT [dbo].[HOADONNHAP] ( [NGAYLAPHDNHAP], [MANCC]) VALUES (N'2021-04-23', 0)
INSERT [dbo].[HOADONNHAP] ( [NGAYLAPHDNHAP], [MANCC]) VALUES (N'2019-04-23', 1)
INSERT [dbo].[HOADONNHAP] ( [NGAYLAPHDNHAP], [MANCC]) VALUES (N'2021-05-07', 2)
INSERT [dbo].[HOADONNHAP] ( [NGAYLAPHDNHAP], [MANCC]) VALUES (N'2020-06-14', 2)
INSERT [dbo].[HOADONNHAP] ( [NGAYLAPHDNHAP], [MANCC]) VALUES (N'2021-09-13', 0)
INSERT [dbo].[HOADONNHAP] ( [NGAYLAPHDNHAP], [MANCC]) VALUES (N'2018-02-24', 4)
INSERT [dbo].[HOADONNHAP] ( [NGAYLAPHDNHAP], [MANCC]) VALUES (N'2022-07-20', 2)
INSERT [dbo].[HOADONNHAP] ( [NGAYLAPHDNHAP], [MANCC]) VALUES (N'2021-10-30', 1)
INSERT [dbo].[HOADONNHAP] ( [NGAYLAPHDNHAP], [MANCC]) VALUES (N'2021-02-28', 0)
INSERT [dbo].[HOADONNHAP] ( [NGAYLAPHDNHAP], [MANCC]) VALUES (N'2022-01-15', 4)


ALTER TABLE [CT_HDBAN] NOCHECK CONSTRAINT ALL
GO
INSERT [dbo].[CT_HDBAN] ([MASACH], [MAHDBAN], [SLBAN], [KHUYENMAI]) VALUES (0, 0, 2, N'NULL')
INSERT [dbo].[CT_HDBAN] ([MASACH], [MAHDBAN], [SLBAN], [KHUYENMAI]) VALUES (1, 1, 2, N'NULL')
INSERT [dbo].[CT_HDBAN] ([MASACH], [MAHDBAN], [SLBAN], [KHUYENMAI]) VALUES (2, 2, 1, N'NULL')
INSERT [dbo].[CT_HDBAN] ([MASACH], [MAHDBAN], [SLBAN], [KHUYENMAI]) VALUES (3, 3, 2, N'NULL')
INSERT [dbo].[CT_HDBAN] ([MASACH], [MAHDBAN], [SLBAN], [KHUYENMAI]) VALUES (4, 4, 3, N'NULL')
INSERT [dbo].[CT_HDBAN] ([MASACH], [MAHDBAN], [SLBAN], [KHUYENMAI]) VALUES (5, 5, 1, N'NULL')
INSERT [dbo].[CT_HDBAN] ([MASACH], [MAHDBAN], [SLBAN], [KHUYENMAI]) VALUES (6, 6, 2, N'NULL')
INSERT [dbo].[CT_HDBAN] ([MASACH], [MAHDBAN], [SLBAN], [KHUYENMAI]) VALUES (7, 7, 1, N'NULL')
INSERT [dbo].[CT_HDBAN] ([MASACH], [MAHDBAN], [SLBAN], [KHUYENMAI]) VALUES (8, 8, 1, N'NULL')

ALTER TABLE [CT_HDNHAP] NOCHECK CONSTRAINT ALL
GO
INSERT [dbo].[CT_HDNHAP] ([MASACH], [MAHDNHAP], [SLNHAP]) VALUES (0, 0, 20)
INSERT [dbo].[CT_HDNHAP] ([MASACH], [MAHDNHAP], [SLNHAP]) VALUES (1, 1, 40)
INSERT [dbo].[CT_HDNHAP] ([MASACH], [MAHDNHAP], [SLNHAP]) VALUES (2, 2, 15)
INSERT [dbo].[CT_HDNHAP] ([MASACH], [MAHDNHAP], [SLNHAP]) VALUES (3, 3, 74)
INSERT [dbo].[CT_HDNHAP] ([MASACH], [MAHDNHAP], [SLNHAP]) VALUES (4, 4, 56)
INSERT [dbo].[CT_HDNHAP] ([MASACH], [MAHDNHAP], [SLNHAP]) VALUES (5, 5, 38)
INSERT [dbo].[CT_HDNHAP] ([MASACH], [MAHDNHAP], [SLNHAP]) VALUES (6, 6, 87)
INSERT [dbo].[CT_HDNHAP] ([MASACH], [MAHDNHAP], [SLNHAP]) VALUES (7, 7, 10)
INSERT [dbo].[CT_HDNHAP] ([MASACH], [MAHDNHAP], [SLNHAP]) VALUES (8, 8, 20)
INSERT [dbo].[CT_HDNHAP] ([MASACH], [MAHDNHAP], [SLNHAP]) VALUES (9, 9, 50)

ALTER TABLE [GIOHANG] NOCHECK CONSTRAINT ALL
GO
INSERT [dbo].[GIOHANG] ([ID_KHACHHANG], [MASACH], [SOLUONG]) VALUES (1, 1, 2)
INSERT [dbo].[GIOHANG] ([ID_KHACHHANG], [MASACH], [SOLUONG]) VALUES (1, 2, 1)
INSERT [dbo].[GIOHANG] ([ID_KHACHHANG], [MASACH], [SOLUONG]) VALUES (1, 6, 2)
INSERT [dbo].[GIOHANG] ([ID_KHACHHANG], [MASACH], [SOLUONG]) VALUES (2, 1, 1)
INSERT [dbo].[GIOHANG] ([ID_KHACHHANG], [MASACH], [SOLUONG]) VALUES (2, 8, 2)
INSERT [dbo].[GIOHANG] ([ID_KHACHHANG], [MASACH], [SOLUONG]) VALUES (3, 1, 2)
INSERT [dbo].[GIOHANG] ([ID_KHACHHANG], [MASACH], [SOLUONG]) VALUES (3, 3, 2)
INSERT [dbo].[GIOHANG] ([ID_KHACHHANG], [MASACH], [SOLUONG]) VALUES (4, 1, 2)
INSERT [dbo].[GIOHANG] ([ID_KHACHHANG], [MASACH], [SOLUONG]) VALUES (4, 9, 2)
INSERT [dbo].[GIOHANG] ([ID_KHACHHANG], [MASACH], [SOLUONG]) VALUES (5, 2, 1)
INSERT [dbo].[GIOHANG] ([ID_KHACHHANG], [MASACH], [SOLUONG]) VALUES (5, 10, 20)
INSERT [dbo].[GIOHANG] ([ID_KHACHHANG], [MASACH], [SOLUONG]) VALUES (6, 1, 5)
INSERT [dbo].[GIOHANG] ([ID_KHACHHANG], [MASACH], [SOLUONG]) VALUES (6, 4, 4)
INSERT [dbo].[GIOHANG] ([ID_KHACHHANG], [MASACH], [SOLUONG]) VALUES (7, 3, 2)
INSERT [dbo].[GIOHANG] ([ID_KHACHHANG], [MASACH], [SOLUONG]) VALUES (7, 1, 2)
INSERT [dbo].[GIOHANG] ([ID_KHACHHANG], [MASACH], [SOLUONG]) VALUES (8, 2, 2)

