//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_WebBanSach05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_HDNHAP
    {
        public int MACT_HDN { get; set; }
        public int MASACH { get; set; }
        public int MAHDNHAP { get; set; }
        public int SLNHAP { get; set; }
    
        public virtual HOADONNHAP HOADONNHAP { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
