//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_WebBanSach05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOHANG
    {
        public int ID_GIOHANG { get; set; }
        public int ID_KHACHHANG { get; set; }
        public int MASACH { get; set; }
        public int SOLUONG { get; set; }
    
        public virtual TK_KHACHHANG TK_KHACHHANG { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
