//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_WebBanSach05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONNHAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADONNHAP()
        {
            this.CT_HDNHAP = new HashSet<CT_HDNHAP>();
        }
    
        public int MAHDNHAP { get; set; }
        public Nullable<System.DateTime> NGAYLAPHDNHAP { get; set; }
        public Nullable<int> MANCC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HDNHAP> CT_HDNHAP { get; set; }
        public virtual NHACC NHACC { get; set; }
    }
}
