//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_WebBanSach05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONBAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADONBAN()
        {
            this.CT_HDBAN = new HashSet<CT_HDBAN>();
        }
    
        public int MAHDBAN { get; set; }
        public Nullable<System.DateTime> NGAYLAPHDBAN { get; set; }
        public int ID_KHACHHANG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HDBAN> CT_HDBAN { get; set; }
        public virtual TK_KHACHHANG TK_KHACHHANG { get; set; }
    }
}
