//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_WebBanSach05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.CT_HDBAN = new HashSet<CT_HDBAN>();
            this.CT_HDNHAP = new HashSet<CT_HDNHAP>();
            this.GIOHANGs = new HashSet<GIOHANG>();
        }
    
        public int MASACH { get; set; }
        public string TENSACH { get; set; }
        public string NGUOIDICH { get; set; }
        public string NGONNGU { get; set; }
        public int SOTRANG { get; set; }
        public int TRONGLUONG { get; set; }
        public string NAMXUATBAN { get; set; }
        public string KICHTHUOC { get; set; }
        public int MATACGIA { get; set; }
        public Nullable<int> MATHELOAI { get; set; }
        public Nullable<int> MANXB { get; set; }
        public string TENANH { get; set; }
        public int GIANHAP { get; set; }
        public int GIABAN { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HDBAN> CT_HDBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HDNHAP> CT_HDNHAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
        public virtual NXB NXB { get; set; }
        public virtual TACGIA TACGIA { get; set; }
        public virtual THELOAI THELOAI { get; set; }
    }
}
