//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_WebBanSach05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOANADMIN
    {
        public int ID_ADMIN { get; set; }
        public string SDT_ADMIN { get; set; }
        public string MATKHAU { get; set; }
    }
}
