//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_WebBanSach05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TK_KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TK_KHACHHANG()
        {
            this.GIOHANGs = new HashSet<GIOHANG>();
            this.HOADONBANs = new HashSet<HOADONBAN>();
        }
    
        public int ID_KHACHHANG { get; set; }
        public string HOTENKH { get; set; }
        public string SDT_KH { get; set; }
        public string DIACHI { get; set; }
        public string MATKHAU_KH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONBAN> HOADONBANs { get; set; }
    }
}
